version: '3'

services:
  browser:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - browser
    environment:
      - SELENIUM_HOST=browser
      - SELENIUM_PORT=4444
      - BROWSER=chrome
      - HEADLESS=true # set this to false if you want to see the tests running in the browser
    command: bash -c "bundle install && bundle exec cucumber"


#version: '3'
#
#services:
#  browser:
#    image: selenium/standalone-firefox:latest
#    ports:
#      - "4444:4444"
#      - "5900:5900"
#    environment:
#      - SCREEN_WIDTH=1920
#      - SCREEN_HEIGHT=1080
#      - JAVA_OPTS=-Dwebdriver.gecko.driver=/usr/bin/geckodriver
#
#  app:
#    build: .
#    volumes:
#      - .:/app
#    depends_on:
#      - browser
#    environment:
#      - SELENIUM_HOST=browser
#      - SELENIUM_PORT=4444
#      - BROWSER=firefox
#      - HEADLESS=true # set this to false if you want to see the tests running in the browser
#    command: bash -c "bundle install && bundle exec cucumber"
