version: "3.7"

services:
  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    env_file:
      - ./..docker/env_files/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./..docker/volumes/postgres_data:/var/lib/postgresql/data

  web:
    image: test
    env_file:
      - ./..docker/env_files/.env
    build:
      context: ../..
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/opt/test:cached
    stdin_open: true
    tty: true

  livereload:
    image: test
    depends_on:
      - web
    ports:
      - 35729:35729
    command: ["bundle", "exec", "guard", "-i"]
    env_file:
      - ./..docker/env_files/.env
    volumes:
      - .:/opt/test:cached

  tailwindcsswatcher:
    image: test
    depends_on:
      - web
    ports:
      - 3035:3035
    command: ["bin/rails", "tailwindcss:watch"]
    env_file:
      - ./..docker/env_files/.env
    volumes:
      - .:/opt/test:cached
    tty: true

  selenium:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - 4444:4444

volumes:
  postgres_data: