name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      #-
      #  name: 'Create docker-compose.yml file'
      #  run: cp .docker/.docker-compose.yml.dev.yml docker-compose.yml
      #-
      #  name: 'Create env file'
      #  run: cp docker/env_files/.env.dev .docker/env_files/.env
      #-
      #  name: Build web container
      #  run: docker-compose.yml build web selenium
      #-
      #  name: 'Create database'
      #  run: docker-compose.yml run --rm web bin/rails db:create db:migrate
      #-
      #  name: 'Start container'
      #  run: docker-compose.yml up -d web selenium
      #-
      #  name: 'Run unit tests'
      #  run: docker-compose.yml exec -T web bin/rails test
      #-
      #  name: 'Run system tests'
      #  run: docker-compose.yml exec -T web bin/rails test:system
      -
        name: 'Run tests'
        run: docker-compose run ruby cucumber