name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: 'docker-compose building..'
        run: docker-compose build
      - name: 'docker-compose up..'
        run: docker-compose up